# Blender Extension Manifest
# https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html

schema_version = "1.0.0"

# Addon Information
id = "blender_civil"
version = "0.1.0"
name = "BlenderCivil"
tagline = "Civil engineering and infrastructure design tools for Blender"
maintainer = "OASYS Contributors"
type = "add-on"

# Supported Blender Versions
blender_version_min = "4.2.0"

# License
license = [
    "SPDX:MIT",
]

# Optional
copyright = [
    "2025 OASYS Contributors",
]

# Website and Documentation
website = "https://github.com/your-username/BlenderCivil"

# Tags for discoverability
tags = [
    "Scene",
    "Object",
    "Pipeline",
    "Import-Export",
]

# Permissions
permissions = [
    "files",
    "network",
]

[permissions.files]
reason = "Import/export alignment data, coordinate system files"

[permissions.network]
reason = "Integration with OASYS cloud platform for coordinate system extraction"

# Optional build settings
[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    ".git/",
    ".github/",
    "docs/",
    "tests/",
    "*.blend",
    "*.blend1",
]
