schema_version = "1.0.0"

id = "blender_civil"
name = "BlenderCivil Native IFC"
tagline = "Professional civil engineering design with native IFC support"
version = "0.4.0"
type = "add-on"

tags = ["Object", "Import-Export", "3D View"]

maintainer = "Desert Springs CE, Michael Yoder"
license = ["SPDX:GPL-3.0-or-later"]

# Blender version requirement
blender_version_min = "4.2.0"

# Permissions - what the extension needs access to
[permissions]
files = "Import/export IFC files"
network = "Download dependency packages (IfcOpenShell)"

# Build configuration
[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    ".git/",
    ".gitignore",
    "*.md",
    "native_ifc_alignment_sprint1_COMPLETE.py",
    "native_ifc_alignment.py",
    "native_ifc_ui_operators_panels.py",
]
